service: pdf-generator-v1

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: eu-central-1
  stage: dev
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: ticket
          method: post
